name: flutter_root_jailbreak_checker
description: A professional Flutter plugin to detect Root (Android) and Jailbreak (iOS) access. Essential for verifying device integrity in security-sensitive apps.
version: 2.0.1

repository: https://github.com/Rehmanalidevpro/flutter_root_jailbreak_checker
issue_tracker: https://github.com/Rehmanalidevpro/flutter_root_jailbreak_checker/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# --- RANKING KE LIYE ZAROORI TOPICS ---
topics:
  - security
  - root-detection
  - jailbreak
  - device-integrity
  - android-ios

flutter:
  plugin:
    platforms:
      android:
        package: com.rehmanali.flutter_root_jailbreak_checker
        pluginClass: FlutterRootJailbreakCheckerPlugin
      ios:
        pluginClass: FlutterRootJailbreakCheckerPlugin